/*

 ROBOT_SPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Robot[] =
{
  0x08,0x08,0x10,0x10,0x20,0x20,0x7E,0x7E,
  0x7E,0x42,0x7E,0x56,0x62,0x5E,0x7E,0x7E
};

/* End of ROBOT_SPRITE.C */
